red_lower_h: 0
red_lower_s: 100
red_lower_v: 135
red_upper_h: 8
red_upper_s: 255
red_upper_v: 255
white_lower_h: 0
white_lower_s: 0
white_lower_v: 178
white_upper_h: 179
white_upper_s: 90
white_upper_v: 255
yellow_lower_h: 6
yellow_lower_s: 97
yellow_lower_v: 154
yellow_upper_h: 48
yellow_upper_s: 200
yellow_upper_v: 255
