white_lower_h: 0
white_lower_s: 0
white_lower_v: 170
white_upper_h: 179
white_upper_s: 48
white_upper_v: 255
yellow_lower_h: 18
yellow_lower_s: 90
yellow_lower_v: 38
yellow_upper_h: 115
yellow_upper_s: 255
yellow_upper_v: 255
